# This automation archives selected repos with LFS objects and saves it to a specific tag
# Contact SIG-Build for any issues or looking to make changes

name: Archive repos

on:
  # Allows you to run this workflow manually from the Actions tag
  workflow_dispatch:
    inputs:
      owner:
        description: 'The org owner'
        required: true
        type: choice
        default: o3de
        options:
          - o3de
      repository:
        description: 'The repo to target for publishing'
        required: true
        type: choice
        default: o3de
        options:
          - o3de
          - o3de-atom-sampleviewer
          - o3de-multiplayersample
          - o3de-multiplayersample-assets
          - o3de-netsoaktest
          - o3de-extras
      branch:
        description: 'The branch to publish'
        required: true
        type: choice
        default: stabilization/2409
        options:
          - main
          - development
          - stabilization/2409
        
run-name: Archiving ${{ inputs.repository }} for ${{ inputs.branch }}

permissions:
  contents: write

jobs:
  Publish:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} # Check environment against branch
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          fetch-depth: 0
      
      - name: Git LFS pull
        run: |
          git lfs install
          git lfs fetch
      
      - name: Get repo vars
        id: vars
        run: |
          VERSION=$(echo "${{ inputs.branch }}" | tr '/' '-')
          echo ::set-output name=latest_log::$(git log --name-status HEAD^..HEAD)
          echo ::set-output name=archive_file::${{ inputs.repository }}-$VERSION
          
      - name: Archive repo as compressed files
        run: |
          git archive -o ${{ steps.vars.outputs.archive_file }}.tar.gz HEAD
      
      - name: Split archive files if over limit
        run: | # MAXSIZE = 2GB
          MAXSIZE=2000000000
          ARCFILE=${{ steps.vars.outputs.archive_file }}
          if [ $(stat -c '%s' $ARCFILE.tar.gz) -ge $MAXSIZE ]; then
            mv $ARCFILE.tar.gz temp-archive.tar.gz && split -b $MAXSIZE temp-archive.tar.gz $ARCFILE.tar.gz.part
          fi
          rm -f temp-archive.*
          
      # Creates a release tag based on inputs
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          replacesArtifacts: true
          removeArtifacts: true
          name: ${{ steps.vars.outputs.archive_file }}
          tag: ${{ steps.vars.outputs.archive_file }}
          body: |
            ${{ steps.vars.outputs.latest_log }}
          artifacts: ${{ steps.vars.outputs.archive_file }}.tar*
